import org.gradle.internal.impldep.org.fusesource.jansi.AnsiRenderer.test

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenCentral()
    maven("https://jitpack.io")
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.maven.apache.org/maven2/")
}

dependencies {
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.0-RC")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    implementation("net.ricecode:string-similarity:1.0.0")
    implementation("com.j256.ormlite:ormlite-jdbc:6.1")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0-RC")
    implementation("org.xerial:sqlite-jdbc:3.42.0.0")
    implementation ("com.github.stefvanschie.inventoryframework:IF:0.10.11")
    compileOnly("io.papermc.paper:paper-api:1.20-R0.1-SNAPSHOT")
}

sourceSets {
    main {
        java {
            srcDir("src/main/resources")
        }
    }
}

group = "plugin.paper"
version = "1.0-SNAPSHOT"
description = "marketplace"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
