/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.samjakob:SpiGUI:1.3")
    api("net.ricecode:string-similarity:1.0.0")
    api("com.j256.ormlite:ormlite-jdbc:6.1")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0-RC")
    api("org.xerial:sqlite-jdbc:3.42.0.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.0-RC")
    testImplementation("junit:junit:RELEASE")
    testImplementation("org.junit.jupiter:junit-jupiter:RELEASE")
    compileOnly("io.papermc.paper:paper-api:1.20-R0.1-SNAPSHOT")
}

group = "plugin.paper"
version = "1.0-SNAPSHOT"
description = "ah"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
