import org.gradle.internal.impldep.org.fusesource.jansi.AnsiRenderer.test

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.0-RC")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    shadow("com.samjakob:SpiGUI:1.3")
    implementation("net.ricecode:string-similarity:1.0.0")
    implementation("com.j256.ormlite:ormlite-jdbc:6.1")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0-RC")
    implementation("org.xerial:sqlite-jdbc:3.42.0.0")
    implementation("io.papermc.paper:paper-api:1.20-R0.1-SNAPSHOT")
}

group = "plugin.paper"
version = "1.0-SNAPSHOT"
description = "ah"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
